-- =========================================================
-- STORAGE SETUP: CORPORATE PROFILE HUB
-- =========================================================

-- 1. Create a bucket for company documents
-- Note: This usually needs to be done via Supabase Dashboard, 
-- but this SQL provides the RLS policies for a bucket named 'company-documents'.

/*
insert into storage.buckets (id, name, public)
values ('company-documents', 'company-documents', false);
*/

-- 2. RLS for storage.objects
create policy "Authenticated users can upload documents"
on storage.objects for insert
with check (
  bucket_id = 'company-documents' AND
  auth.role() = 'authenticated'
);

create policy "Users can view their organization documents"
on storage.objects for select
using (
  bucket_id = 'company-documents' AND
  (storage.foldername(name))[1] in (
    select organization_id::text from public.organization_members where user_id = auth.uid()
  )
);

create policy "Users can delete their organization documents"
on storage.objects for delete
using (
  bucket_id = 'company-documents' AND
  (storage.foldername(name))[1] in (
    select organization_id::text from public.organization_members where user_id = auth.uid()
  )
);

-- Public access policy for Shared Links (Only for specific IDs)
-- This logic usually requires a more refined approach or signed URLs.
-- For now, we'll favor Signed URLs generated by the server.
